services:

  postgres:
    image: postgres:16-alpine
    command: ["postgres", "-c", "max_connections=200"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  post_service:
    build:
      context: .
      dockerfile: builds/post_service/Dockerfile
    env_file:
      - .env
    environment:
      DEBUG: "0"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"
    depends_on:
      - postgres
    restart: always

  comment_service:
    build:
      context: .
      dockerfile: builds/comment_service/Dockerfile
    env_file:
      - .env
    environment:
      DEBUG: "0"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "${COMMENT_SERVICE_PORT}:${COMMENT_SERVICE_PORT}"
    depends_on:
      - postgres
      - redis
    restart: always

  connection_service_1:
    build:
      context: .
      dockerfile: builds/connection_service/Dockerfile
    env_file:
      - .env
    environment:
      DEBUG: "0"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CONNECTION_SERVICE_PORT: ${CONNECTION_SERVICE_PORT_1}
    ports:
      - "${CONNECTION_SERVICE_PORT_1}:${CONNECTION_SERVICE_PORT_1}"
    depends_on:
      - redis
    restart: always

  connection_service_2:
    build:
      context: .
      dockerfile: builds/connection_service/Dockerfile
    env_file:
      - .env
    environment:
      DEBUG: "0"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      CONNECTION_SERVICE_PORT: ${CONNECTION_SERVICE_PORT_2}
    ports:
      - "${CONNECTION_SERVICE_PORT_2}:${CONNECTION_SERVICE_PORT_2}"
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: .
      dockerfile: builds/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - post_service
      - comment_service
      - connection_service_1
      - connection_service_2
    restart: always

volumes:
  pg_data:
  redis_data: