// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "so-many-v2/realtime_comments/services/models"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CommentsRepoI is an autogenerated mock type for the CommentsRepoI type
type CommentsRepoI struct {
	mock.Mock
}

type CommentsRepoI_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentsRepoI) EXPECT() *CommentsRepoI_Expecter {
	return &CommentsRepoI_Expecter{mock: &_m.Mock}
}

// CreateComment provides a mock function with given fields: ctx, _a1
func (_m *CommentsRepoI) CreateComment(ctx context.Context, _a1 *models.CreateComment) (*models.Comment, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 *models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateComment) (*models.Comment, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreateComment) *models.Comment); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreateComment) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentsRepoI_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type CommentsRepoI_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *models.CreateComment
func (_e *CommentsRepoI_Expecter) CreateComment(ctx interface{}, _a1 interface{}) *CommentsRepoI_CreateComment_Call {
	return &CommentsRepoI_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, _a1)}
}

func (_c *CommentsRepoI_CreateComment_Call) Run(run func(ctx context.Context, _a1 *models.CreateComment)) *CommentsRepoI_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreateComment))
	})
	return _c
}

func (_c *CommentsRepoI_CreateComment_Call) Return(_a0 *models.Comment, _a1 error) *CommentsRepoI_CreateComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentsRepoI_CreateComment_Call) RunAndReturn(run func(context.Context, *models.CreateComment) (*models.Comment, error)) *CommentsRepoI_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentButch provides a mock function with given fields: ctx, postID, timeFrom, limit
func (_m *CommentsRepoI) GetCommentButch(ctx context.Context, postID uint, timeFrom time.Time, limit uint) ([]models.Comment, error) {
	ret := _m.Called(ctx, postID, timeFrom, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentButch")
	}

	var r0 []models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, uint) ([]models.Comment, error)); ok {
		return rf(ctx, postID, timeFrom, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, uint) []models.Comment); ok {
		r0 = rf(ctx, postID, timeFrom, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, time.Time, uint) error); ok {
		r1 = rf(ctx, postID, timeFrom, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommentsRepoI_GetCommentButch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentButch'
type CommentsRepoI_GetCommentButch_Call struct {
	*mock.Call
}

// GetCommentButch is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint
//   - timeFrom time.Time
//   - limit uint
func (_e *CommentsRepoI_Expecter) GetCommentButch(ctx interface{}, postID interface{}, timeFrom interface{}, limit interface{}) *CommentsRepoI_GetCommentButch_Call {
	return &CommentsRepoI_GetCommentButch_Call{Call: _e.mock.On("GetCommentButch", ctx, postID, timeFrom, limit)}
}

func (_c *CommentsRepoI_GetCommentButch_Call) Run(run func(ctx context.Context, postID uint, timeFrom time.Time, limit uint)) *CommentsRepoI_GetCommentButch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(time.Time), args[3].(uint))
	})
	return _c
}

func (_c *CommentsRepoI_GetCommentButch_Call) Return(_a0 []models.Comment, _a1 error) *CommentsRepoI_GetCommentButch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CommentsRepoI_GetCommentButch_Call) RunAndReturn(run func(context.Context, uint, time.Time, uint) ([]models.Comment, error)) *CommentsRepoI_GetCommentButch_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommentsRepoI creates a new instance of CommentsRepoI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentsRepoI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentsRepoI {
	mock := &CommentsRepoI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
