// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RedisClientI is an autogenerated mock type for the RedisClientI type
type RedisClientI struct {
	mock.Mock
}

type RedisClientI_Expecter struct {
	mock *mock.Mock
}

func (_m *RedisClientI) EXPECT() *RedisClientI_Expecter {
	return &RedisClientI_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, channel, payload
func (_m *RedisClientI) Publish(ctx context.Context, channel string, payload []byte) error {
	ret := _m.Called(ctx, channel, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, channel, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RedisClientI_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type RedisClientI_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - channel string
//   - payload []byte
func (_e *RedisClientI_Expecter) Publish(ctx interface{}, channel interface{}, payload interface{}) *RedisClientI_Publish_Call {
	return &RedisClientI_Publish_Call{Call: _e.mock.On("Publish", ctx, channel, payload)}
}

func (_c *RedisClientI_Publish_Call) Run(run func(ctx context.Context, channel string, payload []byte)) *RedisClientI_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *RedisClientI_Publish_Call) Return(_a0 error) *RedisClientI_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RedisClientI_Publish_Call) RunAndReturn(run func(context.Context, string, []byte) error) *RedisClientI_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewRedisClientI creates a new instance of RedisClientI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisClientI(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisClientI {
	mock := &RedisClientI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
