// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "so-many-v2/realtime_comments/services/post_service/repository/models"

	mock "github.com/stretchr/testify/mock"
)

// PostRepoI is an autogenerated mock type for the PostRepoI type
type PostRepoI struct {
	mock.Mock
}

type PostRepoI_Expecter struct {
	mock *mock.Mock
}

func (_m *PostRepoI) EXPECT() *PostRepoI_Expecter {
	return &PostRepoI_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function with given fields: ctx, post
func (_m *PostRepoI) CreatePost(ctx context.Context, post *models.CreatePost) (uint, error) {
	ret := _m.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreatePost) (uint, error)); ok {
		return rf(ctx, post)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.CreatePost) uint); ok {
		r0 = rf(ctx, post)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.CreatePost) error); ok {
		r1 = rf(ctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepoI_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type PostRepoI_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - post *models.CreatePost
func (_e *PostRepoI_Expecter) CreatePost(ctx interface{}, post interface{}) *PostRepoI_CreatePost_Call {
	return &PostRepoI_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, post)}
}

func (_c *PostRepoI_CreatePost_Call) Run(run func(ctx context.Context, post *models.CreatePost)) *PostRepoI_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.CreatePost))
	})
	return _c
}

func (_c *PostRepoI_CreatePost_Call) Return(_a0 uint, _a1 error) *PostRepoI_CreatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepoI_CreatePost_Call) RunAndReturn(run func(context.Context, *models.CreatePost) (uint, error)) *PostRepoI_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostById provides a mock function with given fields: ctx, postID
func (_m *PostRepoI) GetPostById(ctx context.Context, postID uint) (*models.Post, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostById")
	}

	var r0 *models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Post, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostRepoI_GetPostById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostById'
type PostRepoI_GetPostById_Call struct {
	*mock.Call
}

// GetPostById is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uint
func (_e *PostRepoI_Expecter) GetPostById(ctx interface{}, postID interface{}) *PostRepoI_GetPostById_Call {
	return &PostRepoI_GetPostById_Call{Call: _e.mock.On("GetPostById", ctx, postID)}
}

func (_c *PostRepoI_GetPostById_Call) Run(run func(ctx context.Context, postID uint)) *PostRepoI_GetPostById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *PostRepoI_GetPostById_Call) Return(_a0 *models.Post, _a1 error) *PostRepoI_GetPostById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PostRepoI_GetPostById_Call) RunAndReturn(run func(context.Context, uint) (*models.Post, error)) *PostRepoI_GetPostById_Call {
	_c.Call.Return(run)
	return _c
}

// NewPostRepoI creates a new instance of PostRepoI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostRepoI(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostRepoI {
	mock := &PostRepoI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
